# Generated by Django 6.0.1 on 2026-01-20 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(default='unidad', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'), models.Index(fields=['is_active'], name='inventory_p_is_acti_47a270_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venta'), ('SALE_VOID', 'Anulación de venta'), ('ADJUST', 'Ajuste'), ('IN', 'Entrada'), ('OUT', 'Salida')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'occurred_at'], name='inventory_s_product_060ca2_idx'), models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx')],
            },
        ),
    ]
