# Generated by Django 6.0.1 on 2026-09-28 05:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HIDRAT', 'Hidratación'), ('SEBOCONT', 'Control de Sebo / Matificante'), ('ANTIAGE', 'Anti-edad / Firmeza'), ('DESPIGM', 'Despigmentante / Aclarador'), ('CALMANTE', 'Calmante / Reparador'), ('PROTSOL', 'Protección Solar'), ('ESTIMCAP', 'Estimulación Capilar')], max_length=20), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('GRASA', 'Piel Grasa'), ('SECA', 'Piel Seca'), ('MIXTA', 'Piel Mixta'), ('SENS', 'Piel Sensible'), ('NORM', 'Piel Normal'), ('TODO', 'Todo Tipo de Piel'), ('CAB_GRASO', 'Cabello Graso'), ('CAB_SECO', 'Cabello Seco')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='target_problems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ACNE', 'Acné'), ('MANCHAS', 'Manchas'), ('ARRUGAS', 'Arrugas'), ('CAIDA', 'Caída de Cabello'), ('CASPA', 'Caspa'), ('ROJEZ', 'Rojez / Irritación'), ('DOLOR', 'Dolor Muscular / Articular')], max_length=20), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['skin_type'], name='inventory_p_skin_ty_17db8e_idx'),
        ),
    ]
