# Generated by Django 6.0.1 on 2026-10-02 04:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_benefits_product_keywords_product_skin_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HIDRAT', 'Hidratación'), ('SEBOCONT', 'Control de Sebo'), ('ANTIAGE', 'Anti-edad / Firmeza'), ('DESPIGM', 'Despigmentante / Aclarador'), ('CALMANTE', 'Calmante / Relajante'), ('PROTSOL', 'Protección Solar'), ('ESTIMCAP', 'Estimulación Capilar'), ('ALIVIO', 'Alivio Rápido / Curativo'), ('LIMPIEZA', 'Limpieza Profunda'), ('DESINFEC', 'Desinfección / Antibacterial'), ('NUTRICION', 'Nutrición / Alimentación'), ('REFRESCANTE', 'Refrescante / Quita Sed'), ('AROMA', 'Aromatizante / Perfumado'), ('ENTRETEN', 'Entretenimiento / Social')], max_length=20), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('GRASA', 'Piel Grasa'), ('SECA', 'Piel Seca'), ('MIXTA', 'Piel Mixta'), ('SENS', 'Piel Sensible'), ('NORM', 'Piel Normal'), ('CAB_GRASO', 'Cabello Graso'), ('CAB_SECO', 'Cabello Seco'), ('CONSUMO', 'Consumo Humano (Abarrotes/Bebidas)'), ('ROPA', 'Cuidado de la Ropa'), ('SUPERFICIES', 'Limpieza de Superficies'), ('SALUD', 'Salud General'), ('TODO', 'Todo Uso')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_problems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ACNE', 'Acné'), ('MANCHAS', 'Manchas en la Piel'), ('ARRUGAS', 'Arrugas / Líneas de expresión'), ('CAIDA', 'Caída de Cabello'), ('CASPA', 'Caspa'), ('ROJEZ', 'Rojez / Irritación'), ('DOLOR', 'Dolor / Malestar General'), ('SUCIEDAD', 'Suciedad / Grasa Doméstica'), ('MANCHAS_ROPA', 'Manchas en Ropa'), ('MAL_OLOR', 'Mal Olor'), ('SED', 'Sed / Deshidratación'), ('HAMBRE', 'Hambre / Antojo'), ('FALTA_ENERGIA', 'Falta de Energía / Deficiencia'), ('NINGUNO', 'Recreación / Ocio')], max_length=20), blank=True, default=list),
        ),
    ]
