# Generated by Django 6.0.1 on 2026-10-07

from decimal import Decimal
from django.db import migrations, models


def migrate_sale_prices_to_stock(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    Stock = apps.get_model("inventory", "Stock")
    Branch = apps.get_model("core", "Branch")

    active_branches = list(Branch.objects.filter(is_active=True))
    if not active_branches:
        return

    # Iterar sobre los productos existentes y copiar su sale_price a Stock para cada sucursal activa
    for product in Product.objects.all():
        sale_price = product.sale_price if product.sale_price is not None else Decimal("0.00")
        for branch in active_branches:
            stock = Stock.objects.filter(branch=branch, product=product).first()
            if stock:
                stock.sale_price = sale_price
                stock.save(update_fields=["sale_price"])
            else:
                Stock.objects.create(
                    branch=branch,
                    product=product,
                    qty_on_hand=Decimal("0.00"),
                    sale_price=sale_price,
                )


def reverse_migrate_sale_prices(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    Stock = apps.get_model("inventory", "Stock")

    # Al revertir, transferir el precio de venta del primer stock existente hacia el producto
    for product in Product.objects.all():
        first_stock = Stock.objects.filter(product=product).first()
        if first_stock:
            product.sale_price = first_stock.sale_price
            product.save(update_fields=["sale_price"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0004_alter_product_benefits_alter_product_skin_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.RunPython(
            code=migrate_sale_prices_to_stock,
            reverse_code=reverse_migrate_sale_prices,
        ),
        migrations.RemoveField(
            model_name="product",
            name="sale_price",
        ),
    ]
