export const POS_ACTIONS = {
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
  SET_RESULTS: "SET_RESULTS",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  SET_PAYMENT_METHOD: "SET_PAYMENT_METHOD",
  SET_ERROR: "SET_ERROR",
  RESET: "RESET",
};
