export const posInitialState = {
  draftSaleId: null,
  draftSale: null,
  branchId: null,
  branchName: "",
  searchTerm: "",
  searchResults: [],
  selectedResultIndex: 0,
  cartItems: [],
  paymentMethod: "CASH",
  serverTotals: {
    subtotal: 0,
    discount: 0,
    tax: 0,
    total: 0,
  },
  syncStatus: "idle",
  lastError: null,
  lastConfirmedSale: null,
  ticketData: null,
};
