# Generated by Django 6.0.1 on 2026-10-08 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('LOW_STOCK', 'Stock Mínimo'), ('NEW_PURCHASE', 'Nueva Compra')], db_index=True, max_length=32, verbose_name='Tipo de notificación')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID de referencia')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.branch', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'is_read'], name='ix_notif_branch_read'), models.Index(fields=['branch', '-created_at'], name='ix_notif_branch_created')],
            },
        ),
    ]
