# Generated by Django 6.0.1 on 2026-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_replace_sale_cashier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='voided_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
