# Generated by Django 6.0.1 on 2026-06-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_cash_payment_amounts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashregistersession',
            name='uq_cash_session_daily_cashier',
        ),
    ]
