# Generated by Django 6.0.1 on 2026-02-13 14:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_code', models.CharField(db_index=True, default='GTQ', max_length=3)),
                ('currency_symbol', models.CharField(default='Q', max_length=8)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1200'), help_text='Tasa IVA. Ej: 0.1200 = 12%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('money_rounding', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Redondeo monetario. Ej: 0.0100 = 2 decimales', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company')),
            ],
            options={
                'db_table': 'config_company_settings',
            },
        ),
    ]
