# Generated by Django 6.0.1 on 2026-02-13 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='sale_void_window_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Minutos para que Sales pueda anular una venta confirmada. 0 = no puede anular.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
