# Generated by Django 6.0.1 on 2026-06-03 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_module', '0002_companysettings_sale_void_window_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='max_cash_sessions_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Número máximo de aperturas/cierres de caja por día.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
