# Generated by Django 6.0.1 on 2026-07-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_module', '0003_companysettings_max_cash_sessions_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='URL del logo de la empresa para visualización en el ticket/recibo.', max_length=512),
        ),
    ]
